#! /usr/bin/env bash
# SPDX-License-Identifier: MIT

###############################   LICENSE TEXT   ###############################
#                                                                              #
#  This file is part of collection of scripts and tools created for my         #
#  personal needs. Usefulness to others might exists                           #
#                                                                              #
#  Copyright © 2020  Chindraba (Ronald Lamoreaux)                              #
#                    <tools@chindraba.work>                                    #
#  - All Rights Reserved                                                       #
#                                                                              #
#  Permission is hereby granted, free of charge, to any person obtaining a     #
#  copy of this software and associated documentation files (the "Software"),  #
#  to deal in the Software without restriction, including without limitation   #
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,    #
#  and/or sell copies of the Software, and to permit persons to whom the       #
#  Software is furnished to do so, subject to the following conditions:        #
#                                                                              #
#  The above copyright notice and this permission notice shall be included in  #
#  all copies or substantial portions of the Software.                         #
#                                                                              #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     #
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         #
#  DEALINGS IN THE SOFTWARE.                                                   #
#                                                                              #
################################################################################

################################   DESCRPTION   ################################
#                                                                              #
#  Update a repository from a remote source and rebase ALL the branches.       #
#  The working tree must be clean, and the current branch should be the        #
#  default branch                                                              #
#                                                                              #
################################################################################

# The remote name must be supplied, as nothing can be presumed to be default.
#
# To "install" this script, place it, or symlink to it, somewhere in your path. If
# the name is kept the git command will execute it like any other git command when
# used as git update-clone, rather than using the command git-update-clone. In
# theory, this will allow the command to be available to other interfaces than just
# the command line.

usage() {
    printf "git %s <%s>\n" "update-clone" "remote name"
    exit 1
}

[ -z "${1}" ] && usage || remote_name="${1}"
curr_branch="$(git branch -a | grep ^\*|awk -e '{printf $2"\n"}')"
git fetch --tags "${remote_name}"
for target_branch in $(git branch -a | grep ${remote_name} | grep -v HEAD | awk -F "${remote_name}/" -e '{printf $2"\n"}'); do
    [ ${target_branch} == "${curr_branch}" ] || { 
        git checkout --quiet "${target_branch}" --
        git rebase --quiet "${remote_name}/${target_branch}"
        git checkout --quiet "${curr_branch}" -- 2>/dev/null
    }
done
git rebase "${remote_name}/${curr_branch}"
