#! /usr/bin/env bash
# SPDX-License-Identifier: MIT

###############################   LICENSE TEXT   ###############################
#                                                                              #
#  This file is part of collection of scripts and tools created for my         #
#  personal needs. Usefulness to others might exists                           #
#                                                                              #
#  Copyright © 2020  Chindraba (Ronald Lamoreaux)                              #
#                    <tools@chindraba.work>                                    #
#  - All Rights Reserved                                                       #
#                                                                              #
#  Permission is hereby granted, free of charge, to any person obtaining a     #
#  copy of this software and associated documentation files (the "Software"),  #
#  to deal in the Software without restriction, including without limitation   #
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,    #
#  and/or sell copies of the Software, and to permit persons to whom the       #
#  Software is furnished to do so, subject to the following conditions:        #
#                                                                              #
#  The above copyright notice and this permission notice shall be included in  #
#  all copies or substantial portions of the Software.                         #
#                                                                              #
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR  #
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,    #
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE #
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      #
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     #
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         #
#  DEALINGS IN THE SOFTWARE.                                                   #
#                                                                              #
################################################################################

################################   DESCRPTION   ################################
#                                                                              #
#  Script to use rsync command optimized for local disk copying                #
#                                                                              #
################################################################################

usage() {
    printf "\tlsync  Command to copy files locally using the rsync command.\n"
    printf "\t       Uses the rsync command with customized options.\n"
    printf "\t       Requires an existing source and a destination.\n\n"
    printf "\t NOTE: The <source> must be a single, valid directory entry.\n"
    printf "\t       Wildcards, shell expansion and globs are not valid. It\n"
    printf "\t       must either be a single directory, which is copied intact,\n"
    printf "\t       or a single file. Use of globs, etc. will have undefined results.\n\n"
    printf "\tUsage: %s <source> <dest>\n" 'lsync'
    exit 1
}

[ -z "$2" ] && usage
[ -e "$1" ] || usage
printf "\tCopying '%s' to '%s' ...\n" "$1" "$2"
rsync --info=PROGRESS2 -ahhWHAXx "$1" "$2"
src_size="$(stat --format=%s "$1")"
dest_size="$(stat --format=%s "$1")"
(( src_size == dest_size )) && \
    result_msg="Copy of %s to %s successfull." || \
    result_msg="Sizes of %s here and in %s do not match.\n\t\tCopy was NOT successfull."
printf "\t\t$result_msg\n" "$1" "$2"

# function cpr() {
#   rsync --archive -hh --hard-links --partial --info=stats1 --info=progress2 --modify-window=1 "$@"
# }
# function mvr() {
#   rsync --archive -hh --hard-links --partial --info=stats1 --info=progress2 --modify-window=1 --remove-source-files "$@"
# }
